# Generated by Django 6.0.6 on 2026-07-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("subheading", models.CharField(max_length=300)),
                ("from_city", models.CharField(default="Chandigarh", max_length=100)),
                ("to_city", models.CharField(default="Anywhere", max_length=100)),
                ("hero_image", models.ImageField(upload_to="hero/")),
            ],
        ),
    ]
