# Generated by Django 6.0.6 on 2026-07-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_route"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("image", models.ImageField(upload_to="hero_slider/")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
