# Generated by Django 6.0.6 on 2026-07-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_heroslider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[("One Way", "One Way"), ("Round Trip", "Round Trip")],
                        max_length=20,
                    ),
                ),
                ("pickup", models.CharField(max_length=200)),
                ("drop", models.CharField(max_length=200)),
                ("pickup_date", models.DateField()),
                ("pickup_time", models.TimeField()),
                ("return_date", models.DateField(blank=True, null=True)),
                ("return_time", models.TimeField(blank=True, null=True)),
                ("phone", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Pending", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ContactSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whatsapp_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "message",
                    models.TextField(
                        default="Once your booking request is received, our team will contact you within 1–2 hours to confirm your booking."
                    ),
                ),
            ],
        ),
    ]
