# Generated by Django 6.0.6 on 2026-08-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_booking_contactsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_logged_in", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_ampm",
            field=models.CharField(
                choices=[("AM", "AM"), ("PM", "PM")], default="AM", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="return_ampm",
            field=models.CharField(
                blank=True,
                choices=[("AM", "AM"), ("PM", "PM")],
                max_length=2,
                null=True,
            ),
        ),
    ]
