# Generated by Django 6.0.6 on 2026-08-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_booking_contactsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="pickup_ampm",
            field=models.CharField(
                choices=[("AM", "AM"), ("PM", "PM")], default="AM", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="return_ampm",
            field=models.CharField(
                blank=True,
                choices=[("AM", "AM"), ("PM", "PM")],
                max_length=2,
                null=True,
            ),
        ),
    ]
