# Generated by Django 6.0.6 on 2026-08-30 13:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_loginuser_booking_pickup_ampm_booking_return_ampm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herosection",
            name="hero_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="hero_image"
            ),
        ),
        migrations.AlterField(
            model_name="heroslider",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="hero_slider_image"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="route_image"
            ),
        ),
    ]
