# Generated by Django 6.0.6 on 2026-08-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_booking_pickup_ampm_booking_return_ampm"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_logged_in", models.BooleanField(default=False)),
            ],
        ),
    ]
