# Generated by Django 6.0.6 on 2026-08-21 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_loginuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginuser",
            name="password",
        ),
    ]
